sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t shiwamkumar/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true shiwamkumar/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region : 'us-east-2'
  app: 'dockerrrs'
  env: 'Dockerrrs-env'
  bucket_name: 'elasticbeanstalk-us-east-2-554661655997'
  bucket_path: "dockerrrs"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
    # secure: AWS_ACCESS_K
  secret_access_key: $AWS_SECRET_KEY