version: '3'

services:
  web:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - /usr/src/node_modules
      - .:/usr/src
  tests: 
  stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes: 
      - /usr/src/node_modules
      - .:/usr/src
    command: npm run test