version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /usr/src/node_modules
      - .:/usr/src
  tests: 
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes: 
      - /usr/src/node_modules
      - .:/usr/src
    command: npm run -e CI=true test